import { Course, ProcessStep, FAQ, Testimonial } from './types';

export const courses: Course[] = [
  {
    id: 'basic-sanskrit',
    title: 'Basic Sanskrit Learning',
    description: 'Build foundational knowledge in Sanskrit — from the alphabet (Varnamala) and basic vocabulary to simple sentence structure. This program is fully flexible and tailored for absolute beginners who want to start their journey into the language of the gods.',
    duration: '1 Hour',
    level: 'Beginner',
    category: 'Personalized',
    batchDetails: '1:1 Personalized | Mode: Online',
    topics: ['Devanagari Alphabet (Varnamala)', 'Basic Vocabulary & Pronunciation', 'Simple Sentence Construction', 'Foundational Conversation Skills'],
    price: '₹450 / hour',
    icon: '📜',
  },
  {
    id: 'advanced-sanskrit',
    title: 'Advanced Sanskrit (Full Grammar)',
    description: 'In-depth study of Sanskrit grammar (Vyakarana), classical literature, and advanced linguistic concepts. Ideal for serious learners seeking complete mastery, including Paninian rules and complex text analysis.',
    duration: '1 Hour',
    level: 'Advanced',
    category: 'Personalized',
    batchDetails: '1:1 Personalized | Mode: Online',
    topics: ['Paninian Grammar (Vyakarana)', 'Classical Literature (Kavya)', 'Compound Words (Samasas) & Sandhis', 'Advanced Syntax & Composition'],
    price: '₹600 / hour',
    icon: '🏛️',
  },
  {
    id: 'basic-shlokas',
    title: 'Shlokas & Scriptures Learning',
    description: 'Learn to chant the Bhagavad Gita, Upanishads, and popular stotras with perfect pronunciation, rhythm (Chhandas), and a deep understanding of their spiritual significance.',
    duration: '1 Hour',
    level: 'Beginner',
    category: 'Scriptures',
    batchDetails: '1:1 Personalized | Mode: Online',
    topics: ['Bhagavad Gita Shlokas', 'Stotras, Mantras & Prayers', 'Chanting Rules (Shiksha)', 'Meaning & Philosophical Context'],
    price: '₹400 / hour',
    icon: '🎼',
  },
  {
    id: 'cbse-sanskrit',
    title: 'CBSE Sanskrit (Academic Support)',
    description: 'Structured academic coaching specifically designed for CBSE students from Grade 5 to 12. We follow the school curriculum closely while building a strong grammatical foundation for exam excellence.',
    duration: '1 Hour',
    level: 'Beginner',
    category: 'Academic',
    batchDetails: 'Grade 5–12 | Mode: Online',
    topics: ['Textbook (Shemushi/Ruchira) Exercises', 'Curriculum-aligned Grammar', 'Exam Strategy & Paper Solving', 'Prose & Poetry Translation'],
    price: '₹500 / hour',
    icon: '🎓',
  },
  {
    id: 'state-board-sanskrit',
    title: 'State Board Sanskrit (Academic)',
    description: 'Targeted academic support for State Board students (Grade 5 to 12). This structured program focuses on curriculum mastery, building subject confidence, and achieving top scores in board examinations.',
    duration: '1 Hour',
    level: 'Beginner',
    category: 'Academic',
    batchDetails: 'Grade 5–12 | Mode: Online',
    topics: ['State Board Curriculum Focus', 'Academic Grammar & Composition', 'Previous Year Paper Analysis', 'Literature & Translation'],
    price: '₹500 / hour',
    icon: '📝',
  },
  {
    id: 'cbse-kannada',
    title: 'CBSE Kannada (Academic Support)',
    description: 'Comprehensive Kannada language coaching for CBSE students (Grade 1 to 12). We help students master reading, writing, and grammar, ensuring they excel in their school assessments.',
    duration: '1 Hour',
    level: 'Beginner',
    category: 'Academic',
    batchDetails: 'Grade 1–12 | Mode: Online',
    topics: ['Kannada Grammar (Vyakarana)', 'Prose, Poetry & Literature', 'Creative Writing Skills', 'Exam Preparation & Practice'],
    price: '₹500 / hour',
    icon: '📖',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Ananya S.',
    location: 'Bangalore',
    rating: 5,
    text: 'The 1:1 sessions have helped my son improve his Sanskrit scores significantly. The teaching style is very patient and simple to understand.',
    avatar: 'https://i.pravatar.cc/150?u=ananya',
    course: 'CBSE Sanskrit (Grade 8)',
  },
  {
    id: 't2',
    name: 'Rajesh Kumar',
    location: 'Hyderabad',
    rating: 5,
    text: 'I started learning Sanskrit as an adult beginner. Sanatanadhara makes it so easy to grasp complex grammar rules. Highly recommended for serious learners!',
    avatar: 'https://i.pravatar.cc/150?u=rajesh',
    course: 'Basic Sanskrit Learning',
  },
  {
    id: 't3',
    name: 'Sowmya V.',
    location: 'Chennai',
    rating: 5,
    text: 'The Shloka chanting sessions are very peaceful and well-structured. My daughter has learned to chant Bhagavad Gita verses with perfect pronunciation.',
    avatar: 'https://i.pravatar.cc/150?u=sowmya',
    course: 'Shlokas & Scriptures',
  },
];

export const howItWorksSteps: ProcessStep[] = [
  {
    id: 1,
    title: 'Contact via WhatsApp or Form',
    description: 'Reach out through WhatsApp or fill in the contact form. We will respond promptly to understand your learning goals and background.',
    icon: '📱',
  },
  {
    id: 2,
    title: 'Attend Free 15-Minute Demo Session',
    description: 'Experience our personalized teaching style with no commitment. A short introductory session to see if we are the right fit for your needs.',
    icon: '🎯',
  },
  {
    id: 3,
    title: 'Start Learning',
    description: 'Once you are comfortable, we finalize the schedule and begin your personalized Sanskrit or Kannada learning journey at your own pace.',
    icon: '🎓',
  },
];

export const faqs: FAQ[] = [
  {
    id: 'faq1',
    question: 'How do I get started?',
    answer: 'Simply contact us via WhatsApp or fill in the contact form. We will schedule a free 15-minute demo session where you can experience our teaching style and discuss your goals.',
  },
  {
    id: 'faq2',
    question: 'Who are these classes suitable for?',
    answer: 'Our classes are suitable for Grade 5 to 12 school students as well as adults — both beginners and advanced learners are welcome.',
  },
  {
    id: 'faq3',
    question: 'In which languages are sessions conducted?',
    answer: 'Sessions can be conducted in English, Sanskrit, Telugu, or Kannada — whichever language you are most comfortable with.',
  },
  {
    id: 'faq4',
    question: 'How are the sessions conducted?',
    answer: 'All sessions are conducted live online — one-on-one, interactive, and fully personalized to your pace and goals.',
  },
  {
    id: 'faq5',
    question: 'What are the fees?',
    answer: 'Fees vary by program: Basic Sanskrit ₹450/hr, Advanced Sanskrit ₹600/hr, Shlokas ₹400/hr, CBSE/State Board Sanskrit ₹500/hr, CBSE Kannada ₹500/hr. A free 15-minute demo is available before you commit.',
  },
];
